version: '3.8'

services:
  # TODO: Add backend service
  # TODO: Add Supabase services (postgres, auth, storage, etc.)
  # TODO: Add ML inference service

  supabase-db:
    image: supabase/postgres:latest
    # TODO: Add configuration

  supabase-auth:
    image: supabase/gotrue:latest
    # TODO: Add configuration

  supabase-storage:
    image: supabase/storage-api:latest
    # TODO: Add configuration
